/**
 * TypeScript mirrors of apps/api/schemas.py Pydantic models.
 * Keep in sync whenever the FastAPI schemas change.
 */

// ── Chat ──────────────────────────────────────────────────────────────────────

export type AssistantMode = "basic" | "awaqi_max";

export interface ChatRequest {
    message: string;
    session_id: string;
    language?: string;
    /** Optional bias for retrieval query embedding (e.g. business vs individual). */
    taxpayer_category?: string | null;
    /** `basic` = single-shot RAG (default). `awaqi_max` = agentic ReAct loop. */
    mode?: AssistantMode;
}

export interface Citation {
    source: string;
    page: number;
    text: string;
    document_title?: string | null;
    proclamation_number?: string | null;
    article_number?: string | null;
    enforcement_status?: string;
    source_url?: string | null;
}

export interface AgentTraceStep {
    step: number;
    type: "tool_call" | "final_answer" | "error";
    tool_name?: string | null;
    tool_args?: Record<string, unknown> | null;
    observation?: Record<string, unknown> | null;
    text?: string | null;
}

export interface ChatResponse {
    response_text: string;
    citations: Citation[];
    confidence_score: number;
    session_token?: string;
    /** Server-side query language hint (Amharic / English / mixed). */
    detected_language?: string | null;
    /** Contextual follow-up question chips generated by the LLM (AWA-30). */
    follow_up_suggestions?: string[];
    mode?: AssistantMode;
    /** Populated only when mode === "awaqi_max". */
    agent_trace?: AgentTraceStep[] | null;
    web_citations?: Array<Record<string, unknown>> | null;
}

export interface ChatSessionItem {
    id: string;
    title?: string | null;
    created_at: string;
    message_count: number;
    last_message_at?: string | null;
}

export interface ChatSessionList {
    sessions: ChatSessionItem[];
}

export interface ChatMessage {
    role: "user" | "assistant" | "system";
    content: string;
    timestamp: string;
    citations?: Citation[] | null;
}

export interface FeedbackRequest {
    score: number;
    comment?: string;
}

// ── Admin ─────────────────────────────────────────────────────────────────────

export interface DocumentStatus {
    doc_id: string;
    status: string;
    duplicate?: boolean;
    processing_stage?: string | null;
    ingest_error?: string | null;
    job_id?: string | null;
}

export interface AdminJobEnqueued {
    job_id: string;
    status: string;
    message: string;
}

export interface JobProgress {
    job_id: string;
    pct: number;
    step: string;
    status: "queued" | "running" | "done" | "failed";
}

export interface LogEntry {
    timestamp: string;
    level: string;
    message: string;
}

export interface LogEntryList {
    logs: LogEntry[];
}

export type EnforcementStatus = "in_effect" | "draft";

export interface AdminDocumentItem {
    id: string;
    title: string;
    status: string;
    enforcement_status: EnforcementStatus;
    source_url?: string | null;
    source_system?: string | null;
    storage_path?: string | null;
    thumbnail_url?: string | null;
    created_at: string;
    processing_stage?: string | null;
    ingest_error?: string | null;
    byte_size?: number | null;
    uploaded_by_id?: string | null;
    uploaded_by_email?: string | null;
    uploaded_by_name?: string | null;
}

export interface AdminDocumentDetail extends AdminDocumentItem {
    file_hash?: string | null;
    registry_key?: string | null;
    storage_path?: string | null;
}

export interface ExtractedPagePreview {
    page_number: number;
    text: string;
    extraction_mode: string;
    ocr_mean_confidence?: number | null;
}

export interface AdminDocumentContentPreview {
    doc_id: string;
    title: string;
    status: string;
    ingest_error?: string | null;
    source_url?: string | null;
    storage_path?: string | null;
    has_stored_pdf: boolean;
    text_source: string;
    pages: ExtractedPagePreview[];
    full_text: string;
    chunk_count: number;
    requires_manual_review: boolean;
    review_reason?: string | null;
    mean_ocr_confidence?: number | null;
    text_quality_warning?: boolean;
    text_quality_reasons?: string[];
    tesseract_langs_installed?: string[];
    ocr_langs_configured?: string;
    ocr_langs_resolved?: string;
}

export interface AdminDocumentList {
    documents: AdminDocumentItem[];
    total: number;
}

export interface AdminDocumentDeleteResult {
    status: string;
    deleted_doc_id: string;
    deleted_chunks: number;
}

export interface AdminScrapeStats {
    discovered: number;
    inserted: number;
    skipped: number;
    errors: number;
}

export interface AdminScrapeResult {
    status: string;
    stats: AdminScrapeStats;
    /** Present when the result came from a queued job response */
    job_id?: string | null;
}

export interface AdminScraperRunItem {
    id: string;
    trigger: string;
    status: string;
    started_at: string;
    finished_at?: string | null;
    stats?: AdminScrapeStats | null;
    error_message?: string | null;
}

export interface AdminScraperRunList {
    runs: AdminScraperRunItem[];
}

export interface AdminScraperConfig {
    seed_urls: string[];
    scheduler_enabled: boolean;
    cron_hour: number;
    cron_minute: number;
    max_links: number;
    storage_dir: string;
    api_base_url: string;
}

export interface AdminScraperConfigPatch {
    seed_urls?: string[];
    scheduler_enabled?: boolean;
    cron_hour?: number;
    cron_minute?: number;
    max_links?: number;
}

export interface AdminScraperStatus {
    scheduler_enabled: boolean;
    cron_hour: number;
    cron_minute: number;
    timezone: string;
    next_run_time?: string | null;
    last_run?: AdminScraperRunItem | null;
}

export type ScrapeSource = "mor_laws" | "ethiodata_tax" | "mor_news";

export interface AdminTelegramScrapeStats {
    messages_seen: number;
    messages_skipped: number;
    documents_inserted: number;
    documents_updated: number;
    errors: number;
    text_posts: number;
    pdf_posts: number;
    pptx_posts: number;
    image_posts: number;
    unsupported: number;
}

export interface AdminTelegramScrapeResult {
    status: string;
    stats: AdminTelegramScrapeStats;
}

export interface AdminTelegramRunItem {
    id: string;
    trigger: string;
    status: string;
    started_at: string;
    finished_at?: string | null;
    stats?: AdminTelegramScrapeStats | null;
    error_message?: string | null;
}

export interface AdminTelegramRunList {
    runs: AdminTelegramRunItem[];
}

export interface AdminTelegramConfig {
    channel_username: string;
    scrape_since: string;
    max_messages_per_run: number;
    scheduler_enabled: boolean;
    cron_hour: number;
    cron_minute: number;
    api_configured: boolean;
    session_configured: boolean;
    next_run_time?: string | null;
}

export interface AdminTelegramConfigPatch {
    channel_username?: string;
    scrape_since?: string;
    max_messages_per_run?: number;
    scheduler_enabled?: boolean;
    cron_hour?: number;
    cron_minute?: number;
}

export interface AdminTelegramClearResult {
    deleted: number;
}

export interface AdminTelegramMessageItem {
    id: string;
    channel_username: string;
    message_id: number;
    content_part: string;
    posted_at: string;
    message_type: string;
    text_preview?: string | null;
    file_name?: string | null;
    mime_type?: string | null;
    byte_size?: number | null;
    telegram_url?: string | null;
    document_id?: string | null;
    document_status?: string | null;
    skip_reason?: string | null;
}

export interface AdminTelegramMessageList {
    messages: AdminTelegramMessageItem[];
    total: number;
}

export interface DocumentStatusCount {
    status: string;
    count: number;
}

export interface AdminAnalytics {
    documents_total: number;
    documents_by_status: DocumentStatusCount[];
    chunks_total: number;
    admin_users_total: number;
    customer_users_total: number;
    chat_sessions_total: number;
    messages_total: number;
    messages_last_7_days: number;
}

export interface AdminSystemHealth {
    database_ok: boolean;
    redis_ok: boolean;
    redis_latency_ms?: number | null;
}

export interface AdminVectorStoreStats {
    configured_dimension: number;
    embedding_model: string;
    column_dimension?: number | null;
    chunks_total: number;
    chunks_with_embedding: number;
    chunks_without_embedding: number;
    storage_bytes: number;
    stored_dimensions: Record<string, number>;
    dimension_mismatch: boolean;
}

export interface AdminVectorStoreActionResult {
    action: string;
    affected_rows: number;
    message: string;
}

// ── Announcements (in-app notifications) ──────────────────────────────────────

export interface Announcement {
    id: string;
    doc_id: string | null;
    doc_title: string;
    summary: string;
    source_url: string | null;
    created_at: string;
}

export interface AnnouncementList {
    announcements: Announcement[];
    total: number;
}

// ── Evaluation (RAG benchmark) ────────────────────────────────────────────────

export type EvaluationMode = "optimized" | "dense_only" | "bm25_only";

export interface EvaluationRunSummary {
    run_id: string;
    mode: EvaluationMode | null;
    /** Answer pipeline used (basic single-shot RAG vs awaqi_max ReAct agent). */
    assistant_mode?: AssistantMode | null;
    k: number | null;
    started_at: string | null;
    finished_at: string | null;
    total_questions: number | null;
    avg_judge_overall: number | null;
    avg_hit_at_k: number | null;
    avg_precision_at_k: number | null;
    avg_recall_at_k: number | null;
    avg_mrr: number | null;
    avg_ndcg_at_k: number | null;
    avg_semantic_similarity: number | null;
    avg_latency_ms: number | null;
    avg_agent_tool_calls?: number | null;
    pct_agent_used_web_search?: number | null;
    benchmark: string | null;
}

export interface EvaluationRunList {
    runs: EvaluationRunSummary[];
}

export interface EvaluationResultItem {
    item_id: string;
    question: string;
    expected_answer: string;
    actual_answer: string;
    language: string;
    topic: string;
    latency_ms: number;
    retrieved_chunk_ids: string[];
    retrieved_doc_ids: string[];
    retrieved_proclamations: (string | null)[];
    relevant_mask: boolean[];
    hit_at_k: number;
    precision_at_k: number;
    recall_at_k: number;
    mrr: number;
    ndcg_at_k: number;
    semantic_similarity: number;
    judge_faithfulness: number;
    judge_answer_relevance: number;
    judge_context_recall: number;
    judge_correctness: number;
    judge_overall: number;
    judge_rationale: string;
    citations: Array<Record<string, unknown>>;
    agent_tool_calls?: number;
    agent_used_web_search?: boolean;
}

export interface EvaluationRunDetail {
    benchmark: string | null;
    summary: EvaluationRunSummary & {
        avg_judge_faithfulness?: number;
        avg_judge_answer_relevance?: number;
        avg_judge_context_recall?: number;
        avg_judge_correctness?: number;
    };
    results: EvaluationResultItem[];
}

export interface EvaluationBenchmarkItem {
    id: string;
    question: string;
    expected_answer: string;
    language: string;
    topic: string;
    ground_truth: {
        proclamation_number: string | null;
        article_numbers: string[];
        keywords: string[];
    };
}

export interface EvaluationBenchmark {
    name: string;
    description: string;
    source_file: string;
    items: EvaluationBenchmarkItem[];
}

export interface UnreadCountResponse {
    unread_count: number;
}

export interface AdminUserItem {
    id: string;
    name?: string | null;
    email: string;
    role: string;
    is_active: boolean;
    created_at: string;
}

export interface AdminUserList {
    users: AdminUserItem[];
}
